#!/usr/bin/env sh

set -e

../scripts/v2-install-texlive \
  --texdir        ~/texlive2 \
  --texuserdir    ~/.texlive2 \
  --texmfhome     ~/texmf2 \
  --tlrc          ~/.tlrc2 \
  --installer-dir ~/.texlive-installer2 \
  --no-adjust-bashrc

source ~/.tlrc2

../scripts/tlmgr-install-extras.pl --dry-run

