#!/usr/bin/env bash

set -e -o pipefail

# DECIDING THE DETAILS OF THE INSTALLATION ********************************

texdir="$HOME/texlive"    # all of your TeX Live goes here
scheme="scheme-minimal"   # the default scheme, "minimal"
tlrc="$HOME/.tlrc"        # the paths for TeX Live
other_opts=""             # other options for install-tl...

while [ $# -gt 0 ]; do
  case "$1" in
    --texdir)
      texdir="$2"
      shift; shift
    ;;
    --scheme)
      scheme="scheme-$2"
      shift; shift
    ;;
    --tlrc)
      tlrc="$2"
      shift; shift
    ;;
    *)
      other_opts="$other_opts $1"
      shift
    ;;
  esac
done

texuserdir="$HOME/.$(basename $texdir)"

if [ -d "$texdir" ]; then
  echo "$texdir already exixts!"
  exit
fi

if [ -d "$texuserdir" ]; then
  echo "$texuserdir already exixts!"
  exit
fi

if [ -f "$tlrc" ]; then
  echo "$tlrc already exixts!"
  exit
fi

# GET READY FOR THE INSTALLATION ******************************************

# Create, if needed, a directory and download there the TeX Live installer.
# !!! This directory will eventually be deleted. This behaviour will likely
# !!! change in future, for it is not unreasonable to keep the installer.

installer_dir="$HOME/.texlive-installer"
[ -d "$installer_dir" ] || mkdir -p "$installer_dir"
cd "$installer_dir"

wget "https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"

tar -xzf install-tl-unx.tar.gz --strip-components 1

# INSTALLATION ************************************************************

# Start the installer with some changes and append certain directories of
# TeX Live to some `PATH`s.

./install-tl --no-interaction           \
             --scheme     "$scheme"     \
             --texdir     "$texdir"     \
             --texuserdir "$texuserdir" \
             $other_opts

cat <<EOF > "$tlrc"
#!/bin/sh
# TeX Live paths.
export PATH=$texdir/bin/x86_64-linux:\$PATH
export MANPATH=$texdir/texmf-dist/doc/man:\$MANPATH
export INFOPATH=$texdir/texmf-dist/doc/info:\$INFOPATH
EOF

# POST INSTALLATION REFINEMENT ********************************************

# After you have done all the work above, prepare the an uninstaller for 
# the installed TeX Live. As you know, you have to annually get rid of TeX
# Live in order to install the newer version. Removing TeX Live should not 
# be difficult (is you remember where you have installed all the stuff), 
# but pay attention to not remove the uninstaller.

cat <<EOF > "$HOME/.texlive-uninstaller"
#!/bin/sh
# The TeX Live uninstaller script
rm -rfv $texdir
rm -rfv $texuserdir
rm -rfv $tlrc
rm -rfv $HOME/.texlive-uninstaller
EOF

chmod u+x ~/.texlive-uninstaller

# END *********************************************************************

cat <<EOF

!!! ABOUT YOUR INSTALLATION

1. Copy the line

   [ -f $tlrc ] && source $tlrc

   at the bottom of your ~/.bashrc, if you haven't done so.

2. The installer is in $installer_dir. That directoy isn't needed
   anymore, thus you can delete it.

3. Here, there is also the script tlmgr-install-extras which installs
   extra packages. If you have selected the full scheme, you do
   not have to worry about this point.

4. To uninstall TeX Live, use the script ~/.texlive-uninstaller

EOF

