#!/usr/bin/env sh

set -e -o pipefail

# DEFAULTS ****************************************************************

# TeX Live installation tree details
texdir=~/texlive       # all of your TeX Live goes here
texuserdir=~/.texlive  # the user installation directory
texmfhome=~/texmf      # the three for the current user
scheme=scheme-minimal  # the dault scheme, "minimal"

# Options for this wrapper sciript only.
installer_dir=~/.texlive-installer  # where the TeX Live installer goes
texliverc=~/.tlrc                   # the paths for TeX Live
#adjust_bashrc=yes                   # register them on ~/.bashrc too?

# Just in case you want to pass other options to install-tl...
other_opts=""

# PARSING COMMAND LINE OPTIONS ********************************************

while [ $# -gt 0 ]; do
  case $1 in
    --texdir)
      texdir="$2"
      shift; shift
    ;;
    --texuserdir)
      texuserdir="$2"
      shift; shift
    ;;
    --texmfhome)
      texmfhome="$2"
      shift; shift
    ;;
    --scheme)
      scheme="scheme-$2"
      shift; shift
    ;;
    --installer-dir)
      installer_dir="$2"
      shift; shift
    ;;
    --tlrc)
      texliverc="$2"
      shift; shift
    ;;
    *)
      other_opts="$other_opts $1"
      shift
    ;;
  esac
done

# GET READY FOR THE INSTALLATION ******************************************

# Create, if needed, a directory and download there the TeX Live installer.
# !!! This directory will eventually be deleted. This behaviour will likely
# !!! change in future, for it is not unreasonable to keep the installer.

[ -d $installer_dir ] || mkdir -p $installer_dir
cd $installer_dir

wget "https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"

tar -xzf install-tl-unx.tar.gz --strip-components 1

# INSTALLATION ************************************************************

# Start the installer with some changes and append certain directories of
# TeX Live to some `PATH`s.

./install-tl \
  --scheme     $scheme \
  --texdir     $texdir \
  --texuserdir $texuserdir \
  --texmfhome  $texmfhome \
  --no-interaction \
  $other_opts

cat <<EOF > $texliverc
#!/bin/sh
# TeX Live paths.
export PATH=$texdir/bin/x86_64-linux:\$PATH
export MANPATH=$texdir/texmf-dist/doc/man:\$MANPATH
export INFOPATH=$texdir/texmf-dist/doc/info:\$INFOPATH
EOF

# Install some highly recommended packages in case the user decides to not
# install the full scheme. This step is quite important: so far, you have
# only a bare skeleton, you cannot even do the most basic stuff.
if [ $scheme != "scheme-full" ]; then
  source $texliverc
  tlmgr install latex-bin
  tlmgr install latex-base-dev
  tlmgr install texlive-scripts
  tlmgr install texdoc
fi

# POST INSTALLATION REFINEMENT ********************************************

# After you have done all the work above, prepare the an uninstaller for 
# the installed TeX Live. As you know, you have to annually get rid of TeX
# Live in order to install the newer version. Removing TeX Live should not 
# be difficult (is you remember where you have installed all the stuff), 
# but pay attention to not remove the uninstaller.

cat <<EOF > ~/.texlive-uninstaller
#!/bin/sh
# The TeX Live uninstaller script
rm -rfv $texdir
rm -rfv $texuserdir
rm -rfv $texmfhome
rm -rfv $texliverc
rm -rfv ~/.texlive-uninstaller
EOF

chmod u+x ~/.texlive-uninstaller

# END *********************************************************************

cat <<EOF

!!! ABOUT YOUR INSTALLATION

1. Copy the line

   [ -f $texliverc ] && source $texliverc

   at the bottom of your ~/.bashrc, if you haven't done so.

2. The installer in $installer_dir. That directoy isn't needed
   anymore, thus you can delete it.

3. In ./scripts there is tlmgr-install-extras.pl which installs
   extra packages. If you have selected the full scheme, you do
   not have to worry about this point.

4. To uninstall TeX Live, use the script ~/.texlive-uninstaller

EOF

