#!/usr/bin/env bash

set -e -o pipefail

# USAGE: get_answer text_prompt default
get_answer () {
  if [ -z "$2" ]; then
    defprompt=""
  else
    defprompt="[default=$2] "
  fi
  read -p "> $1 $defprompt"
  ans=$(echo "$REPLY" | sed -E 's,^\s+,,' | sed -E 's,\s+$,,')
  [ -z "$ans" ] && echo "$2" || echo "$ans"
}

expand_tilde () {
  echo "${1//'~'/$HOME}"
}

cat <<EOF

This script will install TeX Live on your machine.

You will be asked to decide some details of the installation.
If you choose to not answer, the default indicated between the
brackets is assumed. Defaults should be sensible for most of 
the cases.

EOF

read -p "If you want to continue, hit Enter, otherwise Ctrl-C" -n 1

# DETERMINE THE DETAILS FO THE INSTALLATION *******************************

texdir="$(get_answer "where to install TeX Live?" ~/texlive)"
texdir="$(expand_tilde "$texdir")"

if [ -d "$texdir" ]; then
  echo "$texdir already exixts!"
  exit
fi

texuserdir="$HOME/.$(basename $texdir)"

if [ -d "$texuserdir" ]; then
  echo "$texuserdir already exixts!"
  exit
fi

scheme="$(get_answer "select the scheme" scheme-minimal)"

other_options="$(get_answer "any other option for install-tl?")"

tlrc="$(get_answer "where to write paths for TeX Live?" ~/.tlrc)"
tlrc="$(expand_tilde $tlrc)"

if [ -f "$tlrc" ]; then
  echo "$tlrc already exixts!"
  exit
fi

installer_dir="$HOME/.texlive-installer"

# GET READY FOR THE INSTALLATION ******************************************

# Create, if needed, a directory and download there the TeX Live installer.
# !!! This directory will eventually be deleted. This behaviour will likely
# !!! change in future, for it is not unreasonable to keep the installer.

[ -d "$installer_dir" ] || mkdir -p "$installer_dir"
cd "$installer_dir"

wget --continue --no-clobber --no-verbose \
  "https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"

tar -xzf install-tl-unx.tar.gz --strip-components 1

# INSTALLATION ************************************************************

# Start the installer with some changes and add some TeX Live directories
# to `PATH`. Furthermore, craft a simple uninstaller for the installation
# just performed. By the way, removing TeX Live by yourself should not be 
# difficult, but pay attention to not remove the uninstaller.

./install-tl --no-interaction           \
             --scheme     "$scheme"     \
             --texdir     "$texdir"     \
             --texuserdir "$texuserdir" \
             $other_options

cat <<EOF > "$tlrc"
#!/bin/sh
# TeX Live paths.
export PATH=$texdir/bin/x86_64-linux:\$PATH
export MANPATH=$texdir/texmf-dist/doc/man:\$MANPATH
export INFOPATH=$texdir/texmf-dist/doc/info:\$INFOPATH
EOF

cat <<EOF > ~/.texlive-uninstaller
#!/bin/sh
# The TeX Live uninstaller script
rm -rfv $texdir
rm -rfv $texuserdir
rm -rfv $tlrc
rm -rfv $HOME/.texlive-uninstaller
EOF

chmod u+x ~/.texlive-uninstaller

# END *********************************************************************

cat <<EOF | tee ~/.texlive-post-install.txt

### ABOUT YOUR INSTALLATION ###

> Copy the line

  [ -f $tlrc ] && source $tlrc

  at the bottom of your ~/.bashrc, if you haven't done so yet.

> The dir $installer_dir isn't needed anymore: you can delete it.

> To uninstall TeX Live, use the script ~/.texlive-uninstaller.

> If you have installed the minimal-scheme (the default scheme),
  we recommend also to run the script ./tlmgr-install-extras to
  get other basic packages. Read it and edit it.

> This messages is contained in the file ~/.texlive-post-install.txt.
  You can remove it.

EOF

