#!/usr/bin/env sh

# This script installs the TeX Live packages contained in a certain list.

# The list starts right after the line below and terminates with EOF.
cat <<EOF | grep -vP '^\s*(#|$)' | xargs tlmgr install

# We strongly recommend to install the following essential packages.
latex-bin
latex-base-dev
texdoc
texlive-scripts-extra
latexmk

# Modify the list below, instead.

# classes
standalone
suftesi
beamer
memoir

# base packages
fontspec
polyglossia
babel
hyphen-english
hyphen-german
hyphen-french
hyphen-italian
hyphen-greek
microtype
csquotes
hyperref
biblatex
biber
adjustbox
booktabs
imakeidx
geometry
enumitem
xifthen
graphics

# fonts
fontsetup
anyfontsize
libertine
sourcecodepro

# mathematical stuff
libertinust1math
mathalpha
mathtools
mnsymbol
amscls
amsmath
pgf
tikz-cd
commutative-diagrams
extarrows
tcolorbox
thmtools

EOF
