#!/usr/bin/env sh

set -e -o pipefail


# PARSING COMMANDLINE ARGUMENTS *******************************************

# Where all the installed TeX Live goes. It defaults to a directory in your
# home called "texlive".
prefix=~/texlive
# Select the scheme to install. By default, it is "minimal".
scheme=scheme-minimal
# Tell the installer location, that is the directory where to put all the 
# stuff needed for the installation.
installer_dir=~/.texlive-installer
# Verify the installer before running it? By default, do not do it. It is
# recommended to do so, though.
verify_installer=no
# Write a file to be sourced and which exports new paths containing those
# ones of TeX Live
texliverc=~/.tlrc
# By default, adjust ~/.bashrc to register the new paths for TeX Live. 
adjust_bashrc=yes

# Parsing the commandline arguments.
while [ $# -gt 0 ]; do
  case $1 in
    --prefix=*)
      prefix=${1#*=}
      shift
    ;;
    --scheme=*)
      scheme=scheme-${1#*=}
      shift
    ;;
    --installer-dir=*)
      installer_dir=${1#*=}
      shift
    ;;
    --verify-installer)
      verify_installer=yes
      shift
    ;;
    --tlrc=*)
      texliverc=${1#*=}
      shift
    ;;
    --no-adjust-bashrc)
      adjust_bashrc=no
      shift
    ;;
    *)
      echo ":: unknown option: $1"
      exit
    ;;
  esac
done


## PREPARING FOR THE INSTALLER ********************************************

# Let us choose a directory where to download the installer and move there.
[ -d $installer_dir ] || mkdir -p $installer_dir
cd $installer_dir

echo -n ":: download install-tl-unx.tar.gz... "
wget -q https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
if [ $? -eq 0 ]
  then echo "OK"
  else
    echo "ERROR!"
    exit
fi

if [ $verify_installer == yes ]; then
  echo ":: verifying the installer... "
  wget -q http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz.sha512
  wget -q http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz.sha512.asc
  wget -q https://tug.org/texlive/files/texlive.asc
  
  sha512sum -c install-tl-unx.tar.gz.sha512

  gpg --quiet --import texlive.asc
  sig1=$(gpg --list-keys | sed -n '4p' | sed 's/ //g')
  sig2=$(gpg --verify install-tl-unx.tar.gz.sha512.asc 2>&1 | sed -n '7p' | sed -E 's/^[^:]+://;s/ //g')

  if [ $? -eq 0 ]
    then
      echo ":: OK"
    else
      echo ":: Cannot verify!"
      read -n 1 -p ":: continue anyway? (y/n) " ans
      [ $ans = y ] || exit 1
  fi
fi

echo ":: unpacking the installer..."
tar -xzf install-tl-unx.tar.gz --strip-components 1


## INSTALLATION PROCESS ***************************************************

echo ":: starting the installer..."
TEXLIVE_INSTALL_PREFIX=$prefix ./install-tl \
  --scheme $scheme --no-interaction


## POST-INSTALLATION PHASE ************************************************

# Fix PATH, so that we make TeX Live programs visible. To do so, we need to
# extract the year that is also the version of the TeX Live just installed.
year=`sed -n '1p' release-texlive.txt | sed -E 's/^[^0-9]+//g'`

# Write an appropriate file in $HOME.
cat <<EOF > $texliverc
#!/bin/sh

# Adding TeX Live paths...
export PATH=$prefix/$year/bin/x86_64-linux:\$PATH
export MANPATH=$prefix/$year/texmf-dist/doc/man:\$MANPATH
export INFOPATH=$prefix/$year/texmf-dist/doc/info:\$INFOPATH
EOF

[ $adjust_bashrc == yes ] && cat <<EOF >> ~/.bashrc

# Register TeX Live paths
[ -f $texliverc ] && source $texliverc

EOF

# EXPERIMENTAL | After you have done all the work above, prepare the an
# uninstaller for the installed TeX Live.
cat <<EOF > ~/.texlive-uninstaller
#!/bin/sh
rm -rfv $prefix
rm -rfv ~/.texlive*
rm -rfv ~/.texlive-uninstaller
EOF

chmod u+x ~/.texlive-uninstaller

echo ":: END!"

