#!/usr/bin/env sh

set -e

source ~/.tlrc

# Installing some packages we cannot live without, but are not bundled in
# the minimal installation.
tlmgr install latex-bin
tlmgr install texlive-scripts-extra
tlmgr install texdoc
tlmgr install texliveonfly

