#!/usr/bin/env bash

# This script handles the installation of a minimal TeX Live, followed by
# some patches, additional tlmgr packages and other fixes...

# This script is a modification of termux-install-tl which comes bundled
# with the Termux package called texlive-installer.

set -e

# Install two Termux packages, first of all.
pkg install texlive-bin texlive-installer

# Fix PATH
source $PREFIX/etc/profile.d/texlive.sh

# Select the "minimal" scheme instead of the "full" one. This amounts at 
# using a modified version of $PREFIX/opt/texlive/termux.profile bundled in
# the package texlive-installer.
sed 's/scheme-full/scheme-minimal/' \
  $PREFIX/opt/texlive/termux.profile > \
  $PREFIX/opt/texlive/termux-install-minimal.profile

echo -e "\\n:: starting the installer...\\n"
$PREFIX/opt/texlive/install-tl/install-tl \
  --custom-bin $PREFIX/bin/texlive \
  --profile $PREFIX/opt/texlive/termux-install-minimal.profile
  # --profile $PREFIX/opt/texlive/termux.profile

echo -e "\\n:: patching the TeX Live just installed...\\n"
$PREFIX/bin/termux-patch-texlive

echo -e "\\n:: installing some TeX Live packages before...\\n"
tlmgr install texlive-scripts-extra
tlmgr install latex-bin
tlmgr install texliveonfly

echo -e "\\n:: generating missing formats...\\n"
fmtutil-sys --byfmt pdflatex
fmtutil-sys --byfmt lualatex

echo -e "\\n:: conclusive fixes...\\n"
updmap-sys
texlinks

echo -e "\\n:: All done."
echo -e ":: Restart the shell or source $PREFIX/etc/profile.d/texlive.sh to add the TeX Live programs to \$PATH.\\n"

