#!/usr/bin/env sh

set -e -o pipefail

# DEFAULTS | These are some defaults, the names should be explicative.

texdir=~/texlive       # all of your TeX Live goes here
texuserdir=~/.texlive  # the user installation directory
texmfhome=~/texmf      # the three for the current user
scheme=scheme-minimal
installer_dir=~/.texlive-installer
texliverc=~/.tlrc
adjust_bashrc=yes
other_opts=""


# PARSING COMMAND LINE OPTIONS

while [ $# -gt 0 ]; do
  case $1 in
    --texdir)
      texdir=$2
      shift; shift
    ;;
    --texuserdir)
      texuserdir=$2
      shift; shift
    ;;
    --texmfhome)
      texmfhome=$2
      shift; shift
    ;;
    --scheme)
      scheme=scheme-$2
      shift; shift
    ;;
    --installer-dir)
      installer_dir=$2
      shift; shift
    ;;
    --tlrc)
      texliverc=$2
      shift; shift
    ;;
    --no-adjust-bashrc)
      adjust_bashrc=no
      shift
    ;;
    *)
      other_opts="$other_opts $1"
      shift
    ;;
  esac
done


# GET READY FOR THE INSTALLATION

[ -d $installer_dir ] || mkdir -p $installer_dir
cd $installer_dir

wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz

tar -xzf install-tl-unx.tar.gz --strip-components 1

# INSTALLATION
./install-tl \
  --scheme     $scheme \
  --texdir     $texdir \
  --texuserdir $texuserdir \
  --texmfhome  $texmfhome \
  --no-interaction \
  $other_opts

# Write TeX Live paths in a separate file, $texliverc.
cat <<EOF > $texliverc
#!/bin/sh
export PATH=$texdir/bin/x86_64-linux:\$PATH
export MANPATH=$texdir/texmf-dist/doc/man:\$MANPATH
export INFOPATH=$texdir/texmf-dist/doc/info:\$INFOPATH
EOF

# By default, paths are incorporated into ~/.bashrc.
[ $adjust_bashrc = yes ] && cat <<EOF >> ~/.bashrc

# Register TeX Live paths
[ -f $texliverc ] && source $texliverc
EOF

# Install some highly recommended packages in case the user decides to not
# install the full scheme.
if [ $scheme != "scheme-full" ]; then
  source $texliverc
  tlmgr install latex-bin
  tlmgr install latex-base-dev
  tlmgr install texlive-scripts
  tlmgr install texdoc
fi


# POST INSTALLATION REFINEMENT

# After you have done all the work above, prepare the an uninstaller for 
# the installed TeX Live.
cat <<EOF > ~/.texlive-uninstaller
#!/bin/sh
# The TeX Live uninstaller script
rm -rfv $texdir
rm -rfv $texuserdir
rm -rfv $texmfhome
rm -rfv $texliverc
rm -rfv ~/.texlive-uninstaller
EOF

chmod u+x ~/.texlive-uninstaller

# Remove the installer, since it isn't needed anymore.
rm -rf $installer_dir

echo ":: END!"

